version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sequence
      - MORGAN_CONFIG=":id :method :url :status :response-time ms - :res[content-length]"
      - PORT=3000
  mongo:
    image: mongo:4.4
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: